name: Rust Clippy

on: [push, pull_request]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Run Clippy
        run: cargo clippy -- -D warnings
      - name: Build
        run: cargo build --release
